version: '3.8'
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=delivery_tracking
      - MYSQL_ROOT_PASSWORD=Secret-Parcel@77
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=Secret-Parcel@77
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
